version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@1.0.0
jobs:
  simple-test:
    docker: 
      - image: cimg/base:stable
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/continue_config.yml
          parameters: '{"env":"dev"}'
workflows:
  my-workflow:
    jobs:
      - simple-test
