version: 2.1

setup: true

parameters:
  environment:
   type: string
   default: "dev"

orbs:
  continuation: circleci/continuation@1.0.0

jobs:
  simple-test:
    docker: 
      - image: cimg/base:stable
    steps:
      - run: 
          command: echo "Param that was passed in this job was << pipeline.parameters.environment >>"
          name: Capture the parameter passed in the UI or API for this job
      - when:
          condition:
            and:
              - equal: [ dev, << pipeline.parameters.environment >> ]
          steps:
            - checkout
            - continuation/continue:
                configuration_path: .circleci/dev.yml
                parameters: '{"env":"dev"}'
      - when:
          condition:
            and:
              - equal: [ rebuild, << pipeline.parameters.environment >> ]
          steps:
            - checkout
            - continuation/continue:
                configuration_path: .circleci/rebuild.yml
                parameters: '{"rebuild-param-1":"foo"}'
      - when:
          condition:
            and:
              - equal: [ staging, << pipeline.parameters.environment >> ]
          steps:
            - checkout
            - continuation/continue:
                configuration_path: .circleci/staging.yml
                parameters: '{"staging-param-1":"foo", "staging-param-2": true}'

      
workflows:
  my-workflow:
    jobs:
      - simple-test
