version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.3.1
jobs:
  simple-test:
    docker: 
      - image: cimg/base:stable
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/continue_config.yml
workflows:
  my-workflow:
    jobs:
      - simple-test
