version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@1.0.0
jobs:
  simple-test:
    docker: 
      - image: cimg/base:stable
    steps:
      - checkout
      - continuation/continue:
          parameters: { "further": true }
          configuration_path: .circleci/continue_config.yml
workflows:
  setup-workflow:
    jobs:
      - simple-test
