version: 2.1
setup: true
parameters:
  env:
   type: string
   default: "dev"
orbs:
  continuation: circleci/continuation@1.0.0
jobs:
  simple-test:
    docker: 
      - image: cimg/base:stable
    steps:
      - when:
          condition:
            and:
              - equal: [ dev, << pipeline.parameters.env >> ]
          steps:
            - checkout
            - continuation/continue:
                configuration_path: .circleci/dev.yml
                parameters: '{"env":"dev"}'
      - when:
          condition:
            and:
              - equal: [ rebuild, << pipeline.parameters.env >> ]
          steps:
            - checkout
            - continuation/continue:
                configuration_path: .circleci/rebuild.yml
                parameters: '{"rebuild-param-1":"foo"}'
      - when:
          condition:
            and:
              - equal: [ staging, << pipeline.parameters.env >> ]
          steps:
            - checkout
            - continuation/continue:
                configuration_path: .circleci/staging.yml
                parameters: '{"staging-param-1":"foo"}'
workflows:
  my-workflow:
    jobs:
      - simple-test
